export const marketingFooterConfigs = {
  derechoFamilia: {
    brandCopy: 'Estudio jurídico & contable. Litigio estratégico y soluciones 360° para proteger tu núcleo familiar.',
    ctaHeading: '¿Necesitas una asesoría en derecho de familia?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial Saludo%20Koop,%20deseo%20asesor%C3%ADa%20en%20derecho%20de%20familia%20sobre%20el%20siguiente%20tema:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Derecho%20de%20Familia%20Koop',
    serviceTitle: 'Servicios de familia',
    serviceLinks: [
      { label: 'Divorcio y separación', href: '#divorcio' },
      { label: 'Custodia y patria potestad', href: '#custodia' },
      { label: 'Alimentos y pensión alimentaria', href: '#alimentos' },
      { label: 'Violencia intrafamiliar', href: '#sociedad' },
      { label: 'Trámites frente a ICBF o Comisarías de familia', href: '#comisariaseicbf' },
      { label: 'Capitulaciones matrimoniales', href: '#capitulaciones' },
    ],
    phoneNumber: '+57 (350) 396 57 55',
    phoneHref: 'tel:+573503965755',
  },
  derecho: {
    brandCopy: 'Estudio jurídico & contable. Litigio estratégico, cumplimiento y soluciones 360° para la gestión del riesgo laboral.',
    ctaHeading: '¿Necesitas una asesoría laboral hoy?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial Saludo%20Koop,%20deseo%20asesor%C3%ADa%20sobre%20el%20siguiente%20tema:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Laboral%20Koop',
    serviceTitle: 'Áreas de Derecho',
    serviceLinks: [
      { label: 'Derecho penal', to: '/derecho-penal' },
      { label: 'Derecho laboral', to: '/derecho-laboral' },
      { label: 'Trámites notariales', to: '/tramites-notariales' },
      { label: 'Derecho administrativo', to: '/derecho-administrativo' },
    ],
  },
  contabilidad: {
    brandCopy: 'Estudio jurídico & contable. Soluciones integrales para tu empresa.',
    ctaHeading: '¿Necesitas una Asesoría Contable?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial%20Saludo%20Koop,%20deseo%20consultar%20los%20servicios%20contables:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Contabilidad%20Koop',
    serviceTitle: 'Servicios contables',
    serviceLinks: [
      { label: 'Auditoría y Revisoría Fiscal', to: '/auditoria' },
      { label: 'Impuestos y Planeación Tributaria', to: '/impuestos' },
      { label: 'Asesoría Contable', to: '/asesoria-contable' },
    ],
  },
  derechoPenal: {
    brandCopy: 'Estudio jurídico & contable. Litigio estratégico, cumplimiento y soluciones 360° para la gestión del riesgo penal.',
    ctaHeading: '¿Necesitas una asesoría penal hoy?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial Saludo%20Koop,%20deseo%20asesor%C3%ADa%20penal%20sobre%20el%20siguiente%20tema:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Penal%20Koop',
    serviceTitle: 'Servicios penales',
    serviceLinks: [
      { label: 'Audiencias y trámite penal', href: '#audiencias' },
      { label: 'Representación a víctimas', href: '#asesoria' },
      { label: 'Acompañamiento en audiencias', href: '#acompañamiento' },
      { label: 'Habeas corpus y libertades', href: '#habeas' },
      { label: 'Delitos sexuales', href: '#defensa' },
      { label: 'Control ante Fiscalía', href: '#control' },
    ],
  },
  derechoLaboral: {
    brandCopy: 'Estudio jurídico & contable. Litigio estratégico, cumplimiento y soluciones 360° para la gestión del riesgo laboral.',
    ctaHeading: '¿Necesitas una asesoría laboral hoy?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial Saludo%20Koop,%20deseo%20asesor%C3%ADa%20laboral%20sobre%20el%20siguiente%20tema:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Laboral%20Koop',
    serviceTitle: 'Servicios laborales',
    serviceLinks: [
      { label: 'Contrato realidad', href: '#contratorealidad' },
      { label: 'Liquidaciones y prestaciones', href: '#liquidaciones' },
      { label: 'Acoso laboral', href: '#acoso' },
      { label: 'Pensiones y seguridad social', href: '#pensiones' },
      { label: 'Reintegro laboral', href: '#reintegro' },
    ],
  },
  derechoAdministrativo: {
    brandCopy: 'Estudio jurídico & contable. Valoramos y resguardamos tus activos intangibles.',
    ctaHeading: '¿Necesitas una asesoría en derecho administrativo?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial%20Saludo%20Koop,%20deseo%20asesor%C3%ADa%20en%20concencioso%20administrativo%20sobre%20el%20siguiente%20tema:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Derecho%20Administrativo%20Koop',
    serviceTitle: 'Servicios administrativos',
    serviceLinks: [
      { label: 'Gestión urbanística', href: '#peticion' },
      { label: 'Procesos disciplinarios', href: '#disciplinario' },
      { label: 'Contratación estatal', href: '#contratacion' },
      { label: 'Responsabilidad fiscal', href: '#nulidad' },
      { label: 'Conceptos y asesorías', href: '#conceptos' },
    ],
  },
  tramitesNotariales: {
    brandCopy: 'Estudio jurídico & contable. Litigio estratégico, cumplimiento y soluciones 360° para la gestión del riesgo jurídico.',
    ctaHeading: '¿Necesitas una asesoría?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial Saludo%20Koop,%20deseo%20conocer%20los%20costos%20del%20siguiente%20proceso%20notarial:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Notarial%20Koop',
    serviceTitle: 'Servicios notariales',
    serviceLinks: [
      { label: 'Compraventa de inmuebles', href: '#compraventa' },
      { label: 'Constitución o liquidación de sociedades', href: '#constitucion' },
      { label: 'Sucesiones por causa de muerte', href: 'sucesiones' },
      { label: 'Capitulaciones y sociedad conyugal', href: '#capitulaciones' },
      { label: 'Levantamiento de hipotecas', href: '#levantamiento' },
      { label: 'Donaciones de bienes inmuebles', href: '#donaciones' },
    ],
  },
  impuestos: {
    brandCopy: 'Estudio jurídico & contable. Optimización de obligaciones fiscales.',
    ctaHeading: '¿Necesitas una asesoría en impuestos?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial Saludo%20Koop,%20deseo%20asesor%C3%ADa%20en%20impuestos%20sobre%20el%20siguiente%20tema:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Impuestos%20Koop',
    serviceTitle: 'Servicios de impuestos',
    serviceLinks: [
      { label: 'Planeación tributaria', href: '#planeacion' },
      { label: 'Declaraciones y cumplimiento', href: '#declaraciones' },
      { label: 'Defensa ante la DIAN', href: '#dian' },
      { label: 'Precios de transferencia', href: '#transferencia' },
      { label: 'Auditoría fiscal', href: '#auditoria' },
      { label: 'Obligaciones municipales', href: '#municipales' },
    ],
  },
  auditoria: {
    brandCopy: 'Estudio jurídico & contable. Control y transparencia para tu organización.',
    ctaHeading: '¿Necesitas una asesoría en auditoría & revisoría fiscal?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial%20Saludo%20Koop,%20deseo%20asesor%C3%ADa%20en%20auditor%C3%ADa%20y%20revisor%C3%ADa%20fiscal%20sobre%20el%20siguiente%20tema:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Auditor%C3%ADa%20y%20Revisor%C3%ADa%20Fiscal%20Koop',
    serviceTitle: 'Servicios de auditoría',
    serviceLinks: [
      { label: 'Auditoría financiera', href: '#financiera' },
      { label: 'Revisoría fiscal permanente', href: '#revisoria' },
      { label: 'Evaluación de control interno', href: '#control' },
      { label: 'Cumplimiento normativo', href: '#cumplimiento' },
      { label: 'Informes especiales', href: '#informes' },
    ],
  },
  asesoriaContable: {
    brandCopy: 'Estudio jurídico & contable. Continuidad y eficiencia para tu legado.',
    ctaHeading: '¿Necesitas una asesoría en Asesoría Contable?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial%20Saludo%20Koop,%20deseo%20asesor%C3%ADa%20en%20planeaci%C3%B3n%20patrimonial%20sobre%20el%20siguiente%20tema:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Planeaci%C3%B3n%20Patrimonial%20Koop',
    serviceTitle: 'Servicios de asesoría contable',
    serviceLinks: [
      { label: 'Estrategias sucesorales', href: '#sucesion' },
      { label: 'Fideicomisos y patrimonios autónomos', href: '#fideicomisos' },
      { label: 'Protocolos familiares', href: '#protocolos' },
      { label: 'Optimización fiscal del patrimonio', href: '#fiscal' },
      { label: 'Administración de portafolios', href: '#portafolios' },
      { label: 'Protección de activos', href: '#activos' },
    ],
  },
  accionesDeTutela: {
    brandCopy: 'Estudio jurídico & contable. Continuidad y eficiencia para tu legado.',
    ctaHeading: '¿Necesitas una asesoría en Asesoría?',
    whatsappHref: 'https://wa.me/573137213878?text=Cordial%20Saludo%20Koop,%20deseo%20asesor%C3%ADa%20en%20planeaci%C3%B3n%20patrimonial%20sobre%20el%20siguiente%20tema:',
    emailHref: 'mailto:direccionjuridicakoop@hotmail.com?subject=Asesor%C3%ADa%20Planeaci%C3%B3n%20Patrimonial%20Koop',
    serviceTitle: 'Servicios de tutela',
    serviceLinks: [
      { label: 'Derecho de petición', href: '#peticion' },
      { label: 'Tutela en salud', href: '#salud' },
      { label: 'Revocatoria de decisiones judiciales', href: '#revocatoria' },
      { label: 'Tutela para obtener pensión', href: '#tutelapension' },
    ],
  },
};

export const simpleFooterConfigs = {
  home: {
    variant: 'simple',
    simpleLeftText: 'Creado por Koop Strategic Advisory',
    simpleRightLinks: [
      { label: 'Política de Privacidad', href: '/privacidad', target: '_blank' },
    ],
  },
  privacy: {
    variant: 'simple',
    simpleLeftText: 'Creado por Koop Strategic Advisory',
    simpleRightLinks: [
      { label: 'Política de Privacidad', href: '/privacidad' },
    ],
  },
};
